
//Dashboar related actions
export const DASHBOARDGETLOADING ='DASHBOARDGETLOADING'
export const DASHBOARDGETSUCCESS ='DASHBOARDGETSUCCESS'
export const DASHBOARDGETFAILURE ='DASHBOARDGETFAILURE'


//Inventory related actions
export const INVENTORYGETLOADING ='INVENTORYGETLOADING'
export const INVENTORYGETSUCCESS ='INVENTORYGETSUCCESS'
export const INVENTORYGETFAILURE ='INVENTORYGETFAILURE'


export const INVENTORYGET ='INVENTORYGET'